version: '3.8'
services:
  retrospective_app:
    build: .
    ports:
      - "8003:8003"
    depends_on:
      - postgres_db
    volumes:
      - model_data:/app/models
    environment:
      DB_USERNAME: "${DB_USERNAME}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_HOST: "${DB_HOST}"
      DB_NAME: "${DB_NAME}"
      TF_MODEL_ID: "${TF_MODEL_ID}"
      LLM_MODEL_PATH: "${LLM_MODEL_PATH}"
      HF_HOME: "${HF_HOME}"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

      
  postgres_db:
    image: "pgvector/pgvector:0.6.1-pg16"
    environment:
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  model_data:
    external: true
  postgres_data:
    external: true


  
